/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.ine5608.homechef.view;

import br.ufsc.ine5608.homechef.controller.ControladorIngrediente;
import br.ufsc.ine5608.homechef.controller.ControladorItemEstoque;
import br.ufsc.ine5608.homechef.controller.ControladorPrincipal;
import br.ufsc.ine5608.homechef.controller.ControladorReceita;
import br.ufsc.ine5608.homechef.dto.DadosItemEstoque;
import br.ufsc.ine5608.homechef.dto.DadosReceita;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Flávio
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
        List<DadosReceita> receitas;
        List<DadosItemEstoque> estoque;
    public MainForm() {
        initComponents();
        this.receitas = new ArrayList<>();
        this.estoque = new ArrayList<>();
        setLocationRelativeTo(null);
    }
    
    public void setItensEstoque(List<DadosItemEstoque> e) {
        this.estoque = e;
        atualizaTableItensEstoque();
    }
    
    public void setReceitas(List<DadosReceita> r) {
        this.receitas = r;
        atualizaTableReceitas();
    }
    
    private void atualizaTabelas() {
        atualizaTableReceitas();
        atualizaTableItensEstoque();
    }
    
    private void atualizaTableReceitas() {
        //CriaTableModel
        DefaultTableModel dtmodelReceitas = new DefaultTableModel();
        dtmodelReceitas.setColumnIdentifiers(new String[] {"Nome", "Tempo", "Dificuldade", "Possível", "Custo estimado"});
        for (DadosReceita novoDados : this.receitas ) {
            dtmodelReceitas.addRow(new String[] {novoDados.nome,
                                        novoDados.tempo.toString(),
                                        novoDados.dificuldade.getNome(),
                                        "Impossiveeel",
                                        "Custo"});
        }
        //Set table
        this.tableReceitas.setModel(dtmodelReceitas);
    }
    
    private void atualizaTableItensEstoque() {
        DefaultTableModel dtmodelEstoque = new DefaultTableModel();
        dtmodelEstoque.setColumnIdentifiers(new String[] {"Nome", "Quantidade", "Validade"});
        for (DadosItemEstoque novoDados : this.estoque ) {
            dtmodelEstoque.addRow(new String[] {novoDados.ingrediente.getNome(),
                                        String.valueOf(novoDados.quantidade),
                                        novoDados.validade.toString(),
                                        });
        }
        //Set table
        this.tableItemEstoque.setModel(dtmodelEstoque);
    }
    
    public int getIndexDificuldade() {
        return cbDificuldadeReceita.getSelectedIndex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItemEstoque = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableReceitas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbDificuldadeReceita = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbTempoReceita = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNomeReceita = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNomeItemEstoque = new javax.swing.JTextField();
        ckbFiltraReceitasPorIngredienteSelecionado = new javax.swing.JCheckBox();
        ckbFiltraItensVencendoEm10Dias = new javax.swing.JCheckBox();
        btPrepararReceitaSelecionada = new javax.swing.JButton();
        btGerarListaCompras = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEstoque = new javax.swing.JMenu();
        smenuEstoqueEntrada = new javax.swing.JMenuItem();
        smenuEstoqueSaida = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        smenuCadastroIngrediente = new javax.swing.JMenuItem();
        smenuCadastroReceita = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeChef");

        tableItemEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Qtd", "Validade"
            }
        ));
        jScrollPane2.setViewportView(tableItemEstoque);
        if (tableItemEstoque.getColumnModel().getColumnCount() > 0) {
            tableItemEstoque.getColumnModel().getColumn(0).setPreferredWidth(200);
            tableItemEstoque.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        tableReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tempo", "Dificuldade", "Possível", "Custo Estimado"
            }
        ));
        jScrollPane3.setViewportView(tableReceitas);
        if (tableReceitas.getColumnModel().getColumnCount() > 0) {
            tableReceitas.getColumnModel().getColumn(0).setPreferredWidth(200);
            tableReceitas.getColumnModel().getColumn(1).setPreferredWidth(60);
            tableReceitas.getColumnModel().getColumn(2).setPreferredWidth(60);
            tableReceitas.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ingredientes disponíveis:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Receitas:");

        cbDificuldadeReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Fácil", "Média", "Difícil" }));
        cbDificuldadeReceita.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDificuldadeReceitaItemStateChanged(evt);
            }
        });

        jLabel3.setText("Dificuldade:");

        cbTempoReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Até 15min", "De 16min até 30min", "Acima de 30min" }));

        jLabel4.setText("Tempo:");

        jLabel5.setText("Nome:");

        jLabel6.setText("Nome:");

        ckbFiltraReceitasPorIngredienteSelecionado.setText("Listar somente receitas que usam o ingrediente selecionado");

        ckbFiltraItensVencendoEm10Dias.setText("Listar ingredientes que vencerão em 10 dias");

        btPrepararReceitaSelecionada.setText("Preparar Receita Selecionada");
        btPrepararReceitaSelecionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrepararReceitaSelecionadaActionPerformed(evt);
            }
        });

        btGerarListaCompras.setText("Gerar Lista de Compras");

        jMenuBar1.setToolTipText("");

        menuEstoque.setText("Estoque");

        smenuEstoqueEntrada.setText("Entrada de Estoque");
        smenuEstoqueEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smenuEstoqueEntradaActionPerformed(evt);
            }
        });
        menuEstoque.add(smenuEstoqueEntrada);

        smenuEstoqueSaida.setText("Saída de Estoque");
        smenuEstoqueSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smenuEstoqueSaidaActionPerformed(evt);
            }
        });
        menuEstoque.add(smenuEstoqueSaida);

        jMenuBar1.add(menuEstoque);

        menuCadastro.setText("Cadastro");

        smenuCadastroIngrediente.setText("Ingredientes");
        smenuCadastroIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smenuCadastroIngredienteActionPerformed(evt);
            }
        });
        menuCadastro.add(smenuCadastroIngrediente);

        smenuCadastroReceita.setText("Receitas");
        smenuCadastroReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smenuCadastroReceitaActionPerformed(evt);
            }
        });
        menuCadastro.add(smenuCadastroReceita);

        jMenuBar1.add(menuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(tfNomeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTempoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbDificuldadeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ckbFiltraReceitasPorIngredienteSelecionado))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(tfNomeItemEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckbFiltraItensVencendoEm10Dias)))
                                .addGap(0, 74, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btGerarListaCompras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btPrepararReceitaSelecionada)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeItemEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbFiltraItensVencendoEm10Dias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbFiltraReceitasPorIngredienteSelecionado)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTempoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDificuldadeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrepararReceitaSelecionada)
                    .addComponent(btGerarListaCompras))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smenuCadastroIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smenuCadastroIngredienteActionPerformed
        ControladorIngrediente.getInstance().inicia();
    }//GEN-LAST:event_smenuCadastroIngredienteActionPerformed

    private void smenuCadastroReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smenuCadastroReceitaActionPerformed
        ControladorReceita.getInstance().inicia();
    }//GEN-LAST:event_smenuCadastroReceitaActionPerformed

    private void smenuEstoqueEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smenuEstoqueEntradaActionPerformed
        ControladorItemEstoque.getInstance().abreTelaEntradaEstoque();
    }//GEN-LAST:event_smenuEstoqueEntradaActionPerformed

    private void cbDificuldadeReceitaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDificuldadeReceitaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            ControladorPrincipal.getInstance().atualizaReceitas();
        }
    }//GEN-LAST:event_cbDificuldadeReceitaItemStateChanged

    private void btPrepararReceitaSelecionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrepararReceitaSelecionadaActionPerformed
        if (tableReceitas.getSelectedRow() > -1) {
            ControladorReceita.getInstance().abrePepararReceita(receitas.get(tableReceitas.getSelectedRow()));
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma receita!");
        }
    }//GEN-LAST:event_btPrepararReceitaSelecionadaActionPerformed

  private void smenuEstoqueSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smenuEstoqueSaidaActionPerformed
        ControladorItemEstoque.getInstance().abreTelaSaidaEstoque();
    }//GEN-LAST:event_smenuEstoqueSaidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerarListaCompras;
    private javax.swing.JButton btPrepararReceitaSelecionada;
    private javax.swing.JComboBox<String> cbDificuldadeReceita;
    private javax.swing.JComboBox<String> cbTempoReceita;
    private javax.swing.JCheckBox ckbFiltraItensVencendoEm10Dias;
    private javax.swing.JCheckBox ckbFiltraReceitasPorIngredienteSelecionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem smenuCadastroIngrediente;
    private javax.swing.JMenuItem smenuCadastroReceita;
    private javax.swing.JMenuItem smenuEstoqueEntrada;
    private javax.swing.JMenuItem smenuEstoqueSaida;
    private javax.swing.JTable tableItemEstoque;
    private javax.swing.JTable tableReceitas;
    private javax.swing.JTextField tfNomeItemEstoque;
    private javax.swing.JTextField tfNomeReceita;
    // End of variables declaration//GEN-END:variables

}
