/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.ine5608.homechef.view;

import br.ufsc.ine5608.homechef.dto.DadosItemEstoque;
import br.ufsc.ine5608.homechef.dto.DadosReceita;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Flávio
 */
public class PrepararReceita extends javax.swing.JFrame {
    
    private DadosReceita receita;
    private List<DadosItemEstoque> itensEstoque;

    /**
     * Creates new form PrepararReceita
     */
    public PrepararReceita() {
        initComponents();
        itensEstoque = new ArrayList<>();
    }
    
    public void setDados(DadosReceita receita) {
        this.receita = receita;
        setDados();
    }
    
    private void setDados() {
        lbNomeReceita.setText(receita.nome);
        lbTempo.setText(receita.tempo > 0 ? receita.tempo + " min" : "");
        lbDificuldade.setText(receita.dificuldade.getNome());
        txtModoPreparo.setText(receita.modoPreparo);
        carregarItensEstoque();
    }
    
    private void carregarItensEstoque() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbNomeReceita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtModoPreparo = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbTempo = new javax.swing.JLabel();
        lbDificuldade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableIngredientesEstoque = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Preparar Receita");

        jLabel1.setText("Receita:");

        lbNomeReceita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNomeReceita.setText("Macarrão Instantâneo com Molho de Tomate");

        txtModoPreparo.setEditable(false);
        txtModoPreparo.setColumns(20);
        txtModoPreparo.setRows(5);
        txtModoPreparo.setText("Ingredientes:\n1 und - Macarrão Instantâneo\n300 ml  - água\n1 lata - Molho de Tomate\n\nModo de Preparo:\nCozinhe o macarrão por 3 minutos com a água.\nColoque o molho de tomate e ferva por mais 5 minutos.");
        jScrollPane1.setViewportView(txtModoPreparo);

        jButton1.setText("Cancela");

        jButton2.setText("Salva Preparo Receita");

        jLabel3.setText("Tempo:");

        lbTempo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTempo.setText("15 min");

        lbDificuldade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDificuldade.setText("Fácil");

        jLabel6.setText("Dificuldade:");

        jLabel7.setText("Escolha os ingredientes que você utilizará do estoque:");

        tableIngredientesEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Boolean(true), "Água", "2 L", "10/04/2018"},
                { new Boolean(true), "Macarrão Instantâneo", "10 und", "04/08/2019"},
                { new Boolean(true), "Extrato de Tomate", "2 latas", "10/04/2018"},
                {null, "Extrato de Tomate", "1 lata", "25/08/2018"}
            },
            new String [] {
                "Usar", "Ingrediente", "Quantidade", "Validade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableIngredientesEstoque);
        if (tableIngredientesEstoque.getColumnModel().getColumnCount() > 0) {
            tableIngredientesEstoque.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableIngredientesEstoque.getColumnModel().getColumn(1).setPreferredWidth(400);
            tableIngredientesEstoque.getColumnModel().getColumn(2).setPreferredWidth(60);
            tableIngredientesEstoque.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbNomeReceita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lbTempo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lbDificuldade)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbNomeReceita))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbTempo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDificuldade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDificuldade;
    private javax.swing.JLabel lbNomeReceita;
    private javax.swing.JLabel lbTempo;
    private javax.swing.JTable tableIngredientesEstoque;
    private javax.swing.JTextArea txtModoPreparo;
    // End of variables declaration//GEN-END:variables
}
